# Generated by Django 6.0.5 on 2026-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_farm"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("account_manager", "Account Manager (System Admin)"),
                    ("farm_manager", "Farm Manager (Local Admin)"),
                    ("volunteer", "Active Volunteer"),
                    ("friend", "Friend (Read-Only/Legacy)"),
                ],
                default="volunteer",
                max_length=20,
            ),
        ),
    ]
