# Generated by Django 6.0.5 on 2026-05-13 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_avatar"),
        ("farms", "0002_commitmenttier"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="commitment_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteers",
                to="farms.commitmenttier",
            ),
        ),
    ]
