# Generated by Django 6.0.5 on 2026-05-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_commitment_tier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="commitment_tier",
        ),
    ]
