# Generated by Django 6.0.5 on 2026-05-13 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_customuser_commitment_tier"),
        ("farms", "0003_workcommitment_delete_commitmenttier"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="work_commitment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteers",
                to="farms.workcommitment",
            ),
        ),
    ]
