# Generated by Django 6.0.5 on 2026-05-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="legacy_years_volunteered",
            field=models.IntegerField(
                default=0,
                help_text="Number of years volunteered prior to using this system.",
            ),
        ),
    ]
