# Generated by Django 6.0.5 on 2026-05-19 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_customuser_legacy_years_volunteered"),
        ("farms", "0006_farm_liability_waiver_text_farm_onboarding_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_answers", models.JSONField(blank=True, default=dict)),
                ("agreed_to_waiver", models.BooleanField(default=False)),
                (
                    "digital_signature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="farms.farm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "farm")},
            },
        ),
    ]
