# Generated by Django 6.0.5 on 2026-05-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_copy_users_to_memberships"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="farm",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="work_commitment",
        ),
    ]
