# Generated by Django 6.0.5 on 2026-05-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_customuser_farm_and_more"),
        ("farms", "0006_farm_liability_waiver_text_farm_onboarding_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmmembership",
            name="work_commitment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="farms.workcommitment",
            ),
        ),
    ]
