# Generated by Django 6.0.5 on 2026-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsignature",
            name="guardian_relationship",
            field=models.CharField(
                blank=True,
                help_text="e.g., Parent, Legal Guardian",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formsignature",
            name="is_guardian_signature",
            field=models.BooleanField(default=False),
        ),
    ]
