# Generated by Django 6.0.5 on 2026-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_customuser_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(
                blank=True, help_text="Required for legal waivers.", null=True
            ),
        ),
    ]
