# Generated by Django 6.0.5 on 2026-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_customuser_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsignature",
            name="document_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 Cryptographic Hash",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formsignature",
            name="pdf_receipt",
            field=models.FileField(blank=True, null=True, upload_to="waivers/vault/"),
        ),
        migrations.AddField(
            model_name="formsignature",
            name="signer_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
