# Generated by Django 6.0.5 on 2026-05-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_formsignature_document_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.AddField(
            model_name="customuser",
            name="address_line1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Street Address"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address_line2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Apt/Suite/Other"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ZIP/Postal Code"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(
                blank=True, help_text="2-letter abbreviation", max_length=2, null=True
            ),
        ),
    ]
