# Generated by Django 6.0.5 on 2026-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0020_remove_customuser_address_customuser_address_line1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="farmmembership",
            name="applicant_message",
            field=models.TextField(
                blank=True,
                help_text="Message sent by volunteer when requesting to join.",
                null=True,
            ),
        ),
    ]
