# Generated by Django 6.0.5 on 2026-05-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_farmmembership_applicant_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="farming_motto",
            field=models.CharField(
                blank=True,
                help_text="A short blurb visible to Farm Managers about your experience or why you farm.",
                max_length=150,
                null=True,
                verbose_name="Farming Motto",
            ),
        ),
    ]
