# Generated by Django 6.0.6 on 2026-06-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_customuser_farming_motto"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsignature",
            name="is_vaulted",
            field=models.BooleanField(
                default=False,
                help_text="True if successfully synced to AWS S3 Glacier/Vault",
            ),
        ),
    ]
