# Generated by Django 6.0.5 on 2026-05-13 15:42

import django.core.validators
import django.db.models.deletion
import logs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
        ("logs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="crop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="farms.crop",
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="date_logged",
            field=models.DateField(validators=[logs.models.validate_not_in_future]),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="duration_hours",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="Hours must be greater than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        24.0,
                        message="You cannot log more than 24 hours in a single entry.",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="volunteer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="logentry",
            unique_together={
                ("volunteer", "crop", "activity", "date_logged", "duration_hours")
            },
        ),
    ]
