# Generated by Django 6.0.5 on 2026-05-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_alter_logentry_crop_alter_logentry_date_logged_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="activity",
            field=models.CharField(
                choices=[
                    ("P", "Planting"),
                    ("T", "Tending"),
                    ("H", "Harvesting"),
                    ("C", "Cultivating (Weeding)"),
                    ("O", "Off Season Work"),
                    ("M", "Move Dirt"),
                ],
                max_length=1,
            ),
        ),
    ]
