# Generated by Django 6.0.5 on 2026-05-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_alter_logentry_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="notes",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
