# Generated by Django 6.0.5 on 2026-05-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0004_logentry_notes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="logentry",
            unique_together=set(),
        ),
    ]
