# Generated by Django 6.0.5 on 2026-05-13 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_customuser_commitment_tier"),
        ("farms", "0002_commitmenttier"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCommitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("required_hours", models.IntegerField(default=0)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_commitments",
                        to="farms.farm",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CommitmentTier",
        ),
    ]
