# Generated by Django 6.0.5 on 2026-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0003_workcommitment_delete_commitmenttier"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="season_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="season_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
