# Generated by Django 6.0.5 on 2026-05-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0004_farm_season_end_farm_season_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcommitment",
            name="symbol",
            field=models.CharField(
                choices=[
                    ("🌑", "🌑 0% / Empty Moon"),
                    ("🌒", "🌒 25% / Quarter Moon"),
                    ("🌓", "🌓 50% / Half Moon"),
                    ("🌔", "🌔 75% / Three-Quarter Moon"),
                    ("🌕", "🌕 100% / Full Moon"),
                    ("🟢", "🟢 Green Circle"),
                    ("🔵", "🔵 Blue Circle"),
                    ("🟣", "🟣 Purple Circle"),
                    ("🟠", "🟠 Orange Circle"),
                ],
                default="🌕",
                max_length=5,
            ),
        ),
    ]
