# Generated by Django 6.0.5 on 2026-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0005_workcommitment_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="liability_waiver_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="onboarding_schema",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
