# Generated by Django 6.0.5 on 2026-05-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0006_farm_liability_waiver_text_farm_onboarding_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="farm",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="subscription_tier",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
