# Generated by Django 6.0.5 on 2026-05-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0007_farm_is_paid_farm_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="is_comped",
            field=models.BooleanField(
                default=False, help_text="Grants lifetime free access"
            ),
        ),
    ]
