# Generated by Django 6.0.5 on 2026-05-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0008_farm_is_comped"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 2026 General Liability Waiver", max_length=255
                    ),
                ),
                ("body_text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("does_expire", models.BooleanField(default=False)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_forms",
                        to="farms.farm",
                    ),
                ),
            ],
        ),
    ]
