# Generated by Django 6.0.5 on 2026-05-20 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0009_complianceform"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceform",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_compliance_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceform",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("all", "All Volunteers"),
                    ("specific", "Specific Volunteers"),
                ],
                default="all",
                max_length=10,
            ),
        ),
    ]
