# Generated by Django 6.0.5 on 2026-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0010_complianceform_assigned_users_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm",
            name="liability_waiver_text",
        ),
        migrations.AddField(
            model_name="farm",
            name="account_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
