# Generated by Django 6.0.5 on 2026-05-20 15:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0011_remove_farm_liability_waiver_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
