# Generated by Django 6.0.5 on 2026-05-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0012_alter_farm_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="allows_joint_accounts",
            field=models.BooleanField(
                default=False,
                help_text="Bypasses strict legal waiver enforcement to allow families to share a single login. Use with caution.",
            ),
        ),
    ]
