# Generated by Django 6.0.5 on 2026-05-22 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0013_farm_allows_joint_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="farm",
            name="subscription_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("starter", "Starter Plan"),
                    ("growth", "Growth Plan"),
                    ("institutional", "Institutional Plan"),
                ],
                default="starter",
                max_length=50,
                null=True,
            ),
        ),
    ]
