# Generated by Django 6.0.5 on 2026-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0014_alter_farm_created_at_alter_farm_subscription_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="welcome_email_body",
            field=models.TextField(
                default="We're glad to have you on the team. Please use the credentials below to log in."
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="welcome_email_subject",
            field=models.CharField(default="Welcome to the Farm!", max_length=255),
        ),
    ]
