# Generated by Django 6.0.5 on 2026-05-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0015_farm_welcome_email_body_farm_welcome_email_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="welcome_email_body",
            field=models.TextField(default="Welcome to our farm!"),
        ),
        migrations.AlterField(
            model_name="farm",
            name="welcome_email_subject",
            field=models.CharField(default="Welcome!", max_length=255),
        ),
    ]
