# Generated by Django 6.0.5 on 2026-05-23 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0016_alter_farm_welcome_email_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="invite_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
