# Generated by Django 6.0.5 on 2026-05-23 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0018_populate_invite_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="invite_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
