# Generated by Django 6.0.5 on 2026-05-23 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0019_alter_farm_invite_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If True, your farm will appear in the public search directory.",
                    ),
                ),
                (
                    "is_accepting_volunteers",
                    models.BooleanField(
                        default=True,
                        help_text="If False, users can see your profile but the 'Request to Join' button will be hidden.",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="A quick one-sentence hook (max 150 chars).",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "about_us",
                    models.TextField(
                        blank=True,
                        help_text="Rich text HTML generated by the Trix editor.",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of strings e.g., ['USDA Organic', 'No-Till', 'Pesticide-Free']",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="farm_media/logos/"
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="farm_media/covers/"
                    ),
                ),
                ("website_url", models.URLField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                (
                    "farm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="farms.farm",
                    ),
                ),
            ],
        ),
    ]
