# Generated by Django 6.0.5 on 2026-05-24 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0020_farmprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmprofile",
            name="physical_requirements",
            field=models.TextField(
                blank=True,
                help_text="e.g., Must lift 50lbs, kneeling required, 18+ only.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="farmprofile",
            name="volunteer_perks",
            field=models.TextField(
                blank=True,
                help_text="e.g., Free produce, college credit, community meals.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FarmImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="farm_media/gallery/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="farms.farmprofile",
                    ),
                ),
            ],
        ),
    ]
