# Generated by Django 6.0.5 on 2026-05-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0021_farmprofile_physical_requirements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
