# Generated by Django 6.0.5 on 2026-05-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0022_farm_latitude_farm_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm",
            name="address",
        ),
        migrations.AddField(
            model_name="farm",
            name="address_line1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="state",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
